### ISSUE TITLE
Popular for you not working

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/food-recipe-apps#2]
In homepage popular for yout not working, if any feature still on progress show snackbar this feature under development

**Comment by alkarim99** [comment]
![WhatsApp Image 2023-08-10 at 09 09 51](https://github.com/alkarim99/food-recipe-apps/assets/76543950/5ae4c795-120c-43aa-bc08-19546343d420)
I have fix this issue, please check, thanks🙏
